version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongo-container"
        environment: 
            - MONGO_DATA_DIR=data/db
            - MONGO_LOG_DIR=/dev/null
        volumes: 
            - ./mongo-data:/data/db
        ports: 
            - 27017:27017
        restart: always
        command: mongod --profile 1 --slowms 50

    mongo-express:
        image: mongo-express:latest
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
           # - ME_CONFIG_BASICAUTH_USERNAME=basicuser
           # - ME_CONFIG_BASICAUTH_PASSWORD=basicpass
        restart: always
        depends_on:
            - mongodb